# Databricks App Configuration for logfood-central
# See: https://docs.databricks.com/dev-tools/databricks-apps/

# Command to start the app
command: ["streamlit", "run", "app.py", "--server.port", "8000", "--server.enableCORS", "false"]

# Environment variables
env:
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"

# Compute resources
# Using Serverless Starter Warehouse for pm-bootcamp
resources:
  sql_warehouse_id: "9851b1483bb515e6"

# When deployed, the app will use:
# - The Serverless Starter Warehouse for queries
# - App service principal authentication (not user credentials)
# - Serverless compute for running the Streamlit app
