# Databricks App Configuration - Hybrid Architecture
# React Frontend + Python Backend
# See: https://docs.databricks.com/dev-tools/databricks-apps/

# Command to start both frontend and backend
# Builds React frontend, installs backend deps, and runs both services
command: 
  - "sh"
  - "-c"
  - |
    set -e
    echo "📦 Installing frontend dependencies..."
    cd frontend && npm install --production
    echo "🏗️ Building frontend..."
    npm run build
    echo "📦 Installing backend dependencies..."
    cd ../backend && pip install -r requirements.txt
    echo "🚀 Starting Flask API on port 8001..."
    python api.py &
    echo "🌐 Serving frontend on port 8000..."
    cd ../frontend && npx serve -s dist -l 8000

# Environment variables
env:
  - name: DATABRICKS_PROFILE
    value: "pm-bootcamp"
  - name: API_PORT
    value: "8001"

# Compute resources
# Using Serverless Starter Warehouse for pm-bootcamp
resources:
  sql_warehouse_id: "9851b1483bb515e6"

# When deployed, the app will use:
# - The Serverless Starter Warehouse for queries
# - App service principal authentication (managed by Databricks)
# - Frontend on port 8000, Backend API on port 8001